---
name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to suggest a feature!
        Please fill out the following sections to help me understand the request.

  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: >-
        By submitting this issue, you agree to follow the project's
        [Contributing Guidelines](https://github.com/elidholm/server-stats/blob/master/.github/CONTRIBUTING.md).
      options:
        - label: I agree to follow the projects Contributing Guidelines.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you would like to change or add.
      placeholder: Tell me your idea
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: What problem will this solve?
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Description of alternative solutions or features you've considered.
      placeholder: How do you think this should be implemented?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add any other context about the feature request here.
      placeholder: Is there anything else you want to add?
    validations:
      required: false
